#!/usr/bin/env ruby

require 'rubygems'
require 'builder'
require 'nokogiri'
require 'yaml'

def parse_title(doc)
  doc.css("title").text.gsub(/[\n ]+/, " ").strip
end

def parse_attributes(doc)
  attrs = {}
  doc.css("meta").each do |meta_tag|
    next unless meta_tag.attributes.has_key? "name"
    name = meta_tag.attributes["name"].text
    case name
    when /^DC\./
      attrs[name] = meta_tag.attributes["content"].text
    end
  end
  attrs["title"] = parse_title(doc)
  attrs["plone_url"] = doc.css("base")[0].attributes["href"].text
  attrs
end

def parse_content(doc)
  doc.css("div.documentContent").children.to_s
end

def create_file_index(dir)
  # TODO: could set a class based on whether item is
  # a file or a directory.  For files we could compute size
  # and directories possibly number of items inside.
  adir = File.expand_path(dir)
  xm = Builder::XmlMarkup.new(:indent => 2, :margin => 8)
  content = xm.ul("class" => "file_list") {
    Dir["#{adir}/*"].each do |f|
      xm.li { xm.a(f, "href" => f) }
    end
  }.to_s
  attrs = {
    "title" => "#{File.basename(adir)}",
    "created_at" => Time.now.to_s,
    "autogenerated" => "true"
  }
  { :content => content, :attrs => attrs }
end

##
# import plone workshop index_html into nanoc content
#
# input should be the path to the workshops directory
# as exported from Plone containing the index_html files
#
# content should be the path to the nanoc content directory.
def import_workshop_index_files(input, content)
  indir = File.expand_path(input)
  outdir = File.expand_path(content)
  workshop_out_dir = "#{outdir}/#{File.basename(indir)}"
  Dir.chdir(input) do
    Dir["**/*"].each do |f|
      if File.basename(f) == "index_html"
        puts "processing: #{input}/#{f}"
        dest_dir = "#{workshop_out_dir}/#{File.dirname(f)}"
        FileUtils.mkdir_p(dest_dir)
        doc = Nokogiri::HTML(open("#{indir}/#{f}"))
        print "."
        attrs = parse_attributes(doc)
        print "."
        content = parse_content(doc)
        puts "."
        open("#{dest_dir}/index.html", "w") do |out|
          out.write(content)
        end
        open("#{dest_dir}/index.yaml", "w") do |out|
          out.write(attrs.to_yaml)
        end
      end
    end
  end
end

# infile = ARGV[0]
# puts "processing: #{infile}"

# doc = Nokogiri::HTML(open(infile))
# attrs = parse_attributes(doc)
# content = parse_content(doc)
# open("test1.html", "w") do |f|
#   f.write(content)
# end
# open("test1.yaml", "w") do |f|
#   f.write(attrs.to_yaml)
# end

import_workshop_index_files("plone-bioconductor.org/workshops", "contents")
