raise 'Ruby version must be 2.3 or greater' unless  RUBY_VERSION.to_f >= 2.3
source 'http://rubygems.org'
gem "nanoc", "~> 4.12"
gem "pry"
gem "pry-byebug"
gem "rdiscount"
gem "rack"
gem "mime-types"
gem "haml"
gem "rack-cache"
gem "httparty"
gem "rake"
gem "sass"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "mechanize"
gem "json"
gem "nokogiri"
gem "rgl"
gem "sqlite3"
gem "adsf"
gem "twitter"
gem "hpricot"
gem "uuid"
gem "htmlentities"
gem "redis"
gem "descriptive_statistics"
gem "sequel"
gem "pg"
gem "treetop-dcf"
gem "octokit"

# Ruby 3.x moved these from default to *bundled* gems, so bundler excludes them
# from the load path unless they are declared here. Required by lib/ and scripts/.
gem "rexml"
gem "rss"
