#!/usr/bin/env ruby

require 'rubygems'
require 'hpricot'
require 'yaml'

class PloneConverter

  def initialize(file_path, dest_id, selector = "div.documentContent")
    @doc = Hpricot(open(file_path))
    @dest_id = dest_id
    @selector = selector
  end

  def parse_title
    puts "using selector: #{@selector}"
    @doc.search("title").inner_html.gsub(/[\n ]+/, " ").strip
  end

  def parse_attributes
    attrs = {}
    @doc.search("meta").each do |meta_tag|
      name = meta_tag["name"]
      next unless name
      case name
      when /^DC\./
        attrs[name] = meta_tag["content"]
      end
    end
    attrs["title"] = parse_title()
    attrs["plone_url"] = @doc.search("base")[0]["href"]
    attrs
  end

  def parse_content
    @doc.search(@selector).inner_html
  end

  def convert
    unless (@dest_id =~ /^\/.*\/$/)
      raise "dest_id must start/end with /"
    end
    dest_path = "content#{@dest_id}"
    dest_html = dest_path.chop + ".html"
    dest_yaml = dest_path.chop + ".yaml"
    attrs = parse_attributes()
    content = parse_content()
    open(dest_html, "w") do |out|
      out.write(content)
    end
    open(dest_yaml, "w") do |out|
      out.write(attrs.to_yaml)
    end
    [dest_html, dest_yaml]
  end
end

USAGE = <<EOF
Usage: #{$0} infile nanoc_id selector

infile - path to input HTML file that you want to convert

nanoc_id - determines the output file according to nanoc_id syntax.
           Basically this is the relative URL for the output.
           E.g. /about/foo/.

selector - A string to identify the div in which the main HTML content
           is living.  Most likely one of "div.documentContent" or
           "div.plain"

EOF

if __FILE__ == $0
  if ARGV.count != 3
    puts USAGE
    exit 1
  end
  plone_file, dest_id, selector = ARGV
  converter = PloneConverter.new(plone_file, dest_id, selector)
  output = converter.convert
  puts "Wrote output to:"
  output.each do |f|
    puts "    #{f}"
  end
end
