name: Pr Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency: preview-${{ github.ref }}
jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "2.6.5"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: build website
        run: |
          pwd
          rake
          cd output
          ls -la

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./output/
          custom-url: https://nearform.github.io/bioconductor.org/pr-preview/pr-1/output/
