name: Pr - Preview
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  dev-pr-create-s3:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "2.6.5"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: build website
        run: rake

      - name: Deploy S3 Website
        uses: danburtenshaw/s3-website-pr-action@v2.0.1
        with:
          bucket-prefix: "pr-preview-bioconductor"
          folder-to-copy: "./output"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
