name: deploy to staging environment

on:
  workflow_dispatch:
jobs:
  staging:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/redesign2023'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "2.6.5"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build website
        run: |
          rake
      - name: Deploy website to staging s3
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: output
          bucket: ${{secrets.S3_BUCKET}}
          bucket-region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
