name: deploy to staging environment

on:
  workflow_dispatch:
jobs:
  staging:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install and Build
        run: printf "would build and install here :)\n"
      - name: Deploy Staging
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./output/
